# Generated by Django 5.0.4 on 2024-05-26 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0002_alter_product_options_alter_purchase_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={},
        ),
    ]
